<?php

namespace Styde\Enlighten\Console\Commands;

use Illuminate\Console\Command;
use Styde\Enlighten\Models\Run;

class ExportDocumentationCommand extends Command
{
    protected $name = 'enlighten:export';

    protected $description = 'Export the documentation generated by Enlighten as static HTML files';

    public function handle()
    {
        $runs = $this->getLatestRuns();

        $answer = $this->choice(
            "Please select the run you'd like to export",
            $runs->pluck('signature')->all(),
            $runs->first()->signature
        );

        $this->info($answer);
    }

    protected function getLatestRuns()
    {
        return Run::query()
            ->latest()
            ->take(5)
            ->get();
    }
}
